### ISSUE TITLE
Missing a Template Image called "None"

### ISSUE THREAD

**Issue by giyuer** [Samsterr/SirSquirrelAssistant#55]
2024-12-31 01:00:16,316 - src.mirror - DEBUG - []
2024-12-31 01:00:16,316 - src.mirror - DEBUG - set()
2024-12-31 01:00:16,316 - src.mirror - DEBUG - [(1080, 197), (1080, 517), (1080, 836)]
2024-12-31 01:00:16,316 - src.mirror - DEBUG - [(1080, 197), (1080, 517), (1080, 836)]
2024-12-31 01:00:21,643 - src.mirror - INFO - Restshop
2024-12-31 01:00:21,643 - src.mirror - INFO - Starting Fusion
2024-12-31 01:00:24,571 - __main__ - ERROR - Template image 'None' not found.
Traceback (most recent call last):
  File "sirsquirrel.py", line 43, in mirror_dungeon_run
  File "src\mirror.py", line 127, in mirror_loop
  File "src\mirror.py", line 552, in rest_shop
  File "src\mirror.py", line 475, in fuse_gifts
  File "src\common.py", line 326, in click_matching
  File "src\common.py", line 338, in element_exist
  File "src\common.py", line 103, in match_image
FileNotFoundError: Template image 'None' not found.

-- Stuck at Fusion
-- Error Image: https://github.com/user-attachments/assets/a0cc3722-15d8-4a0c-ae84-9e38f4a082c8
-- I downloaded the newest hotfix

**Comment by Samsterr** [comment]
@giyuer does this issue exist when you use the older hotfix just to verify?

**Comment by Samsterr** [comment]
@giyuer should be resolved in the update i will be posting

**Comment by giyuer** [comment]
ight thank you 🙏
