### ISSUE TITLE
Still getting the Template image 'None' not found.

### ISSUE THREAD

**Issue by giyuer** [Samsterr/SirSquirrelAssistant#56]
2024-12-31 16:38:05,982 - src.mirror - INFO - Restshop
2024-12-31 16:38:05,982 - src.mirror - INFO - Starting Fusion
2024-12-31 16:38:08,455 - __main__ - ERROR - Template image 'None' not found.
Traceback (most recent call last):
  File "sirsquirrel.py", line 56, in mirror_dungeon_run
  File "src\mirror.py", line 127, in mirror_loop
  File "src\mirror.py", line 555, in rest_shop
  File "src\mirror.py", line 480, in fuse_gifts
  File "src\common.py", line 326, in click_matching
  File "src\common.py", line 338, in element_exist
  File "src\common.py", line 103, in match_image
FileNotFoundError: Template image 'None' not found.

Error From CMD: [ WARN:0@395.106] global loadsave.cpp:241 cv::findDecoder imread_(''): can't open/read file: check file path/integrity

(Downloaded newest version)

**Comment by Samsterr** [comment]
@giyuer are u using slash/blunt/pierce by chance

**Comment by giyuer** [comment]
oh yeah im using slash

**Comment by Samsterr** [comment]
@giyuer temporarily try not to use slash. i forgot to add fusion images for it after mdh update

**Comment by giyuer** [comment]
ight 👍
